runtime: python
env: flex
entrypoint: streamlit run  "📑Data Upload.py" --server.port $PORT

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.10"
  service: claims-analysis

manual_scaling:
  instances: 1
